//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connect_to_ELMA_API.ELMA_SOAP {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebData", Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    [System.SerializableAttribute()]
    public partial class WebData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Connect_to_ELMA_API.ELMA_SOAP.WebDataItem[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Connect_to_ELMA_API.ELMA_SOAP.WebDataItem[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebDataItem", Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    [System.SerializableAttribute()]
    public partial class WebDataItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Connect_to_ELMA_API.ELMA_SOAP.WebData DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Connect_to_ELMA_API.ELMA_SOAP.WebData[] DataArrayField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Connect_to_ELMA_API.ELMA_SOAP.WebData Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Connect_to_ELMA_API.ELMA_SOAP.WebData[] DataArray {
            get {
                return this.DataArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.DataArrayField, value) != true)) {
                    this.DataArrayField = value;
                    this.RaisePropertyChanged("DataArray");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskInfo", Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    [System.SerializableAttribute()]
    public partial class TaskInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        private long ExecutorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExecutorNameField;
        
        private System.DateTime CreationDateField;
        
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Connect_to_ELMA_API.ELMA_SOAP.ConnectorInfo[] ConnectorInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long ExecutorId {
            get {
                return this.ExecutorIdField;
            }
            set {
                if ((this.ExecutorIdField.Equals(value) != true)) {
                    this.ExecutorIdField = value;
                    this.RaisePropertyChanged("ExecutorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ExecutorName {
            get {
                return this.ExecutorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ExecutorNameField, value) != true)) {
                    this.ExecutorNameField = value;
                    this.RaisePropertyChanged("ExecutorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public Connect_to_ELMA_API.ELMA_SOAP.ConnectorInfo[] ConnectorInfo {
            get {
                return this.ConnectorInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectorInfoField, value) != true)) {
                    this.ConnectorInfoField = value;
                    this.RaisePropertyChanged("ConnectorInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectorInfo", Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    [System.SerializableAttribute()]
    public partial class ConnectorInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid UIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid UID {
            get {
                return this.UIDField;
            }
            set {
                if ((this.UIDField.Equals(value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkflowMessageSendResult", Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    [System.SerializableAttribute()]
    public partial class WorkflowMessageSendResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ReceivedCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ReceivedCount {
            get {
                return this.ReceivedCountField;
            }
            set {
                if ((this.ReceivedCountField.Equals(value) != true)) {
                    this.ReceivedCountField = value;
                    this.RaisePropertyChanged("ReceivedCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/", ConfigurationName="ELMA_SOAP.WFPWebServiceSoap")]
    public interface WFPWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name userName from namespace http://www.elma-bpm.ru/WFPWebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/Run", ReplyAction="*")]
        Connect_to_ELMA_API.ELMA_SOAP.RunResponse Run(Connect_to_ELMA_API.ELMA_SOAP.RunRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/Run", ReplyAction="*")]
        System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.RunResponse> RunAsync(Connect_to_ELMA_API.ELMA_SOAP.RunRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://www.elma-bpm.ru/WFPWebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/GetStatus", ReplyAction="*")]
        Connect_to_ELMA_API.ELMA_SOAP.GetStatusResponse GetStatus(Connect_to_ELMA_API.ELMA_SOAP.GetStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/GetStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.GetStatusResponse> GetStatusAsync(Connect_to_ELMA_API.ELMA_SOAP.GetStatusRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://www.elma-bpm.ru/WFPWebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/LoadContext", ReplyAction="*")]
        Connect_to_ELMA_API.ELMA_SOAP.LoadContextResponse LoadContext(Connect_to_ELMA_API.ELMA_SOAP.LoadContextRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/LoadContext", ReplyAction="*")]
        System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.LoadContextResponse> LoadContextAsync(Connect_to_ELMA_API.ELMA_SOAP.LoadContextRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://www.elma-bpm.ru/WFPWebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/GetActiveTasks", ReplyAction="*")]
        Connect_to_ELMA_API.ELMA_SOAP.GetActiveTasksResponse GetActiveTasks(Connect_to_ELMA_API.ELMA_SOAP.GetActiveTasksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/GetActiveTasks", ReplyAction="*")]
        System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.GetActiveTasksResponse> GetActiveTasksAsync(Connect_to_ELMA_API.ELMA_SOAP.GetActiveTasksRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://www.elma-bpm.ru/WFPWebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/ExecuteTask", ReplyAction="*")]
        Connect_to_ELMA_API.ELMA_SOAP.ExecuteTaskResponse ExecuteTask(Connect_to_ELMA_API.ELMA_SOAP.ExecuteTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/ExecuteTask", ReplyAction="*")]
        System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.ExecuteTaskResponse> ExecuteTaskAsync(Connect_to_ELMA_API.ELMA_SOAP.ExecuteTaskRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://www.elma-bpm.ru/WFPWebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/SaveContext", ReplyAction="*")]
        Connect_to_ELMA_API.ELMA_SOAP.SaveContextResponse SaveContext(Connect_to_ELMA_API.ELMA_SOAP.SaveContextRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/SaveContext", ReplyAction="*")]
        System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.SaveContextResponse> SaveContextAsync(Connect_to_ELMA_API.ELMA_SOAP.SaveContextRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://www.elma-bpm.ru/WFPWebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/Terminate", ReplyAction="*")]
        Connect_to_ELMA_API.ELMA_SOAP.TerminateResponse Terminate(Connect_to_ELMA_API.ELMA_SOAP.TerminateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/Terminate", ReplyAction="*")]
        System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.TerminateResponse> TerminateAsync(Connect_to_ELMA_API.ELMA_SOAP.TerminateRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://www.elma-bpm.ru/WFPWebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/SendMessage", ReplyAction="*")]
        Connect_to_ELMA_API.ELMA_SOAP.SendMessageResponse SendMessage(Connect_to_ELMA_API.ELMA_SOAP.SendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/SendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.SendMessageResponse> SendMessageAsync(Connect_to_ELMA_API.ELMA_SOAP.SendMessageRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://www.elma-bpm.ru/WFPWebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/SendMessageToInstance", ReplyAction="*")]
        Connect_to_ELMA_API.ELMA_SOAP.SendMessageToInstanceResponse SendMessageToInstance(Connect_to_ELMA_API.ELMA_SOAP.SendMessageToInstanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/SendMessageToInstance", ReplyAction="*")]
        System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.SendMessageToInstanceResponse> SendMessageToInstanceAsync(Connect_to_ELMA_API.ELMA_SOAP.SendMessageToInstanceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Run", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Connect_to_ELMA_API.ELMA_SOAP.RunRequestBody Body;
        
        public RunRequest() {
        }
        
        public RunRequest(Connect_to_ELMA_API.ELMA_SOAP.RunRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class RunRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string instanceName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Connect_to_ELMA_API.ELMA_SOAP.WebData data;
        
        public RunRequestBody() {
        }
        
        public RunRequestBody(string userName, string password, string token, string instanceName, Connect_to_ELMA_API.ELMA_SOAP.WebData data) {
            this.userName = userName;
            this.password = password;
            this.token = token;
            this.instanceName = instanceName;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RunResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Connect_to_ELMA_API.ELMA_SOAP.RunResponseBody Body;
        
        public RunResponse() {
        }
        
        public RunResponse(Connect_to_ELMA_API.ELMA_SOAP.RunResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class RunResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long RunResult;
        
        public RunResponseBody() {
        }
        
        public RunResponseBody(long RunResult) {
            this.RunResult = RunResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatus", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Connect_to_ELMA_API.ELMA_SOAP.GetStatusRequestBody Body;
        
        public GetStatusRequest() {
        }
        
        public GetStatusRequest(Connect_to_ELMA_API.ELMA_SOAP.GetStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class GetStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long instanceId;
        
        public GetStatusRequestBody() {
        }
        
        public GetStatusRequestBody(string userName, string password, long instanceId) {
            this.userName = userName;
            this.password = password;
            this.instanceId = instanceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Connect_to_ELMA_API.ELMA_SOAP.GetStatusResponseBody Body;
        
        public GetStatusResponse() {
        }
        
        public GetStatusResponse(Connect_to_ELMA_API.ELMA_SOAP.GetStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class GetStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetStatusResult;
        
        public GetStatusResponseBody() {
        }
        
        public GetStatusResponseBody(int GetStatusResult) {
            this.GetStatusResult = GetStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadContextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadContext", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Connect_to_ELMA_API.ELMA_SOAP.LoadContextRequestBody Body;
        
        public LoadContextRequest() {
        }
        
        public LoadContextRequest(Connect_to_ELMA_API.ELMA_SOAP.LoadContextRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class LoadContextRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long instanceId;
        
        public LoadContextRequestBody() {
        }
        
        public LoadContextRequestBody(string userName, string password, long instanceId) {
            this.userName = userName;
            this.password = password;
            this.instanceId = instanceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadContextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadContextResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Connect_to_ELMA_API.ELMA_SOAP.LoadContextResponseBody Body;
        
        public LoadContextResponse() {
        }
        
        public LoadContextResponse(Connect_to_ELMA_API.ELMA_SOAP.LoadContextResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class LoadContextResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Connect_to_ELMA_API.ELMA_SOAP.WebData LoadContextResult;
        
        public LoadContextResponseBody() {
        }
        
        public LoadContextResponseBody(Connect_to_ELMA_API.ELMA_SOAP.WebData LoadContextResult) {
            this.LoadContextResult = LoadContextResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActiveTasksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActiveTasks", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Connect_to_ELMA_API.ELMA_SOAP.GetActiveTasksRequestBody Body;
        
        public GetActiveTasksRequest() {
        }
        
        public GetActiveTasksRequest(Connect_to_ELMA_API.ELMA_SOAP.GetActiveTasksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class GetActiveTasksRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long instanceId;
        
        public GetActiveTasksRequestBody() {
        }
        
        public GetActiveTasksRequestBody(string userName, string password, long instanceId) {
            this.userName = userName;
            this.password = password;
            this.instanceId = instanceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActiveTasksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActiveTasksResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Connect_to_ELMA_API.ELMA_SOAP.GetActiveTasksResponseBody Body;
        
        public GetActiveTasksResponse() {
        }
        
        public GetActiveTasksResponse(Connect_to_ELMA_API.ELMA_SOAP.GetActiveTasksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class GetActiveTasksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Connect_to_ELMA_API.ELMA_SOAP.TaskInfo[] GetActiveTasksResult;
        
        public GetActiveTasksResponseBody() {
        }
        
        public GetActiveTasksResponseBody(Connect_to_ELMA_API.ELMA_SOAP.TaskInfo[] GetActiveTasksResult) {
            this.GetActiveTasksResult = GetActiveTasksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteTask", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Connect_to_ELMA_API.ELMA_SOAP.ExecuteTaskRequestBody Body;
        
        public ExecuteTaskRequest() {
        }
        
        public ExecuteTaskRequest(Connect_to_ELMA_API.ELMA_SOAP.ExecuteTaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class ExecuteTaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long taskId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string connectorUid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Connect_to_ELMA_API.ELMA_SOAP.WebData data;
        
        public ExecuteTaskRequestBody() {
        }
        
        public ExecuteTaskRequestBody(string userName, string password, long taskId, string connectorUid, Connect_to_ELMA_API.ELMA_SOAP.WebData data) {
            this.userName = userName;
            this.password = password;
            this.taskId = taskId;
            this.connectorUid = connectorUid;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteTaskResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Connect_to_ELMA_API.ELMA_SOAP.ExecuteTaskResponseBody Body;
        
        public ExecuteTaskResponse() {
        }
        
        public ExecuteTaskResponse(Connect_to_ELMA_API.ELMA_SOAP.ExecuteTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ExecuteTaskResponseBody {
        
        public ExecuteTaskResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveContextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveContext", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Connect_to_ELMA_API.ELMA_SOAP.SaveContextRequestBody Body;
        
        public SaveContextRequest() {
        }
        
        public SaveContextRequest(Connect_to_ELMA_API.ELMA_SOAP.SaveContextRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class SaveContextRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long instanceId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Connect_to_ELMA_API.ELMA_SOAP.WebData data;
        
        public SaveContextRequestBody() {
        }
        
        public SaveContextRequestBody(string userName, string password, long instanceId, Connect_to_ELMA_API.ELMA_SOAP.WebData data) {
            this.userName = userName;
            this.password = password;
            this.instanceId = instanceId;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveContextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveContextResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Connect_to_ELMA_API.ELMA_SOAP.SaveContextResponseBody Body;
        
        public SaveContextResponse() {
        }
        
        public SaveContextResponse(Connect_to_ELMA_API.ELMA_SOAP.SaveContextResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveContextResponseBody {
        
        public SaveContextResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TerminateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Terminate", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Connect_to_ELMA_API.ELMA_SOAP.TerminateRequestBody Body;
        
        public TerminateRequest() {
        }
        
        public TerminateRequest(Connect_to_ELMA_API.ELMA_SOAP.TerminateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class TerminateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long instanceId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string reason;
        
        public TerminateRequestBody() {
        }
        
        public TerminateRequestBody(string userName, string password, long instanceId, string reason) {
            this.userName = userName;
            this.password = password;
            this.instanceId = instanceId;
            this.reason = reason;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TerminateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TerminateResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Connect_to_ELMA_API.ELMA_SOAP.TerminateResponseBody Body;
        
        public TerminateResponse() {
        }
        
        public TerminateResponse(Connect_to_ELMA_API.ELMA_SOAP.TerminateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TerminateResponseBody {
        
        public TerminateResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Connect_to_ELMA_API.ELMA_SOAP.SendMessageRequestBody Body;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(Connect_to_ELMA_API.ELMA_SOAP.SendMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class SendMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string messageTypeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Connect_to_ELMA_API.ELMA_SOAP.WebData data;
        
        public SendMessageRequestBody() {
        }
        
        public SendMessageRequestBody(string userName, string password, string messageTypeName, Connect_to_ELMA_API.ELMA_SOAP.WebData data) {
            this.userName = userName;
            this.password = password;
            this.messageTypeName = messageTypeName;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Connect_to_ELMA_API.ELMA_SOAP.SendMessageResponseBody Body;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(Connect_to_ELMA_API.ELMA_SOAP.SendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class SendMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Connect_to_ELMA_API.ELMA_SOAP.WorkflowMessageSendResult SendMessageResult;
        
        public SendMessageResponseBody() {
        }
        
        public SendMessageResponseBody(Connect_to_ELMA_API.ELMA_SOAP.WorkflowMessageSendResult SendMessageResult) {
            this.SendMessageResult = SendMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageToInstanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageToInstance", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Connect_to_ELMA_API.ELMA_SOAP.SendMessageToInstanceRequestBody Body;
        
        public SendMessageToInstanceRequest() {
        }
        
        public SendMessageToInstanceRequest(Connect_to_ELMA_API.ELMA_SOAP.SendMessageToInstanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class SendMessageToInstanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long instanceId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string messageTypeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Connect_to_ELMA_API.ELMA_SOAP.WebData data;
        
        public SendMessageToInstanceRequestBody() {
        }
        
        public SendMessageToInstanceRequestBody(string userName, string password, long instanceId, string messageTypeName, Connect_to_ELMA_API.ELMA_SOAP.WebData data) {
            this.userName = userName;
            this.password = password;
            this.instanceId = instanceId;
            this.messageTypeName = messageTypeName;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageToInstanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageToInstanceResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Connect_to_ELMA_API.ELMA_SOAP.SendMessageToInstanceResponseBody Body;
        
        public SendMessageToInstanceResponse() {
        }
        
        public SendMessageToInstanceResponse(Connect_to_ELMA_API.ELMA_SOAP.SendMessageToInstanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class SendMessageToInstanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Connect_to_ELMA_API.ELMA_SOAP.WorkflowMessageSendResult SendMessageToInstanceResult;
        
        public SendMessageToInstanceResponseBody() {
        }
        
        public SendMessageToInstanceResponseBody(Connect_to_ELMA_API.ELMA_SOAP.WorkflowMessageSendResult SendMessageToInstanceResult) {
            this.SendMessageToInstanceResult = SendMessageToInstanceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WFPWebServiceSoapChannel : Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WFPWebServiceSoapClient : System.ServiceModel.ClientBase<Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap>, Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap {
        
        public WFPWebServiceSoapClient() {
        }
        
        public WFPWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WFPWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WFPWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WFPWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Connect_to_ELMA_API.ELMA_SOAP.RunResponse Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap.Run(Connect_to_ELMA_API.ELMA_SOAP.RunRequest request) {
            return base.Channel.Run(request);
        }
        
        public long Run(string userName, string password, string token, string instanceName, Connect_to_ELMA_API.ELMA_SOAP.WebData data) {
            Connect_to_ELMA_API.ELMA_SOAP.RunRequest inValue = new Connect_to_ELMA_API.ELMA_SOAP.RunRequest();
            inValue.Body = new Connect_to_ELMA_API.ELMA_SOAP.RunRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.token = token;
            inValue.Body.instanceName = instanceName;
            inValue.Body.data = data;
            Connect_to_ELMA_API.ELMA_SOAP.RunResponse retVal = ((Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap)(this)).Run(inValue);
            return retVal.Body.RunResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.RunResponse> Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap.RunAsync(Connect_to_ELMA_API.ELMA_SOAP.RunRequest request) {
            return base.Channel.RunAsync(request);
        }
        
        public System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.RunResponse> RunAsync(string userName, string password, string token, string instanceName, Connect_to_ELMA_API.ELMA_SOAP.WebData data) {
            Connect_to_ELMA_API.ELMA_SOAP.RunRequest inValue = new Connect_to_ELMA_API.ELMA_SOAP.RunRequest();
            inValue.Body = new Connect_to_ELMA_API.ELMA_SOAP.RunRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.token = token;
            inValue.Body.instanceName = instanceName;
            inValue.Body.data = data;
            return ((Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap)(this)).RunAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Connect_to_ELMA_API.ELMA_SOAP.GetStatusResponse Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap.GetStatus(Connect_to_ELMA_API.ELMA_SOAP.GetStatusRequest request) {
            return base.Channel.GetStatus(request);
        }
        
        public int GetStatus(string userName, string password, long instanceId) {
            Connect_to_ELMA_API.ELMA_SOAP.GetStatusRequest inValue = new Connect_to_ELMA_API.ELMA_SOAP.GetStatusRequest();
            inValue.Body = new Connect_to_ELMA_API.ELMA_SOAP.GetStatusRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            Connect_to_ELMA_API.ELMA_SOAP.GetStatusResponse retVal = ((Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap)(this)).GetStatus(inValue);
            return retVal.Body.GetStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.GetStatusResponse> Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap.GetStatusAsync(Connect_to_ELMA_API.ELMA_SOAP.GetStatusRequest request) {
            return base.Channel.GetStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.GetStatusResponse> GetStatusAsync(string userName, string password, long instanceId) {
            Connect_to_ELMA_API.ELMA_SOAP.GetStatusRequest inValue = new Connect_to_ELMA_API.ELMA_SOAP.GetStatusRequest();
            inValue.Body = new Connect_to_ELMA_API.ELMA_SOAP.GetStatusRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            return ((Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap)(this)).GetStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Connect_to_ELMA_API.ELMA_SOAP.LoadContextResponse Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap.LoadContext(Connect_to_ELMA_API.ELMA_SOAP.LoadContextRequest request) {
            return base.Channel.LoadContext(request);
        }
        
        public Connect_to_ELMA_API.ELMA_SOAP.WebData LoadContext(string userName, string password, long instanceId) {
            Connect_to_ELMA_API.ELMA_SOAP.LoadContextRequest inValue = new Connect_to_ELMA_API.ELMA_SOAP.LoadContextRequest();
            inValue.Body = new Connect_to_ELMA_API.ELMA_SOAP.LoadContextRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            Connect_to_ELMA_API.ELMA_SOAP.LoadContextResponse retVal = ((Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap)(this)).LoadContext(inValue);
            return retVal.Body.LoadContextResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.LoadContextResponse> Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap.LoadContextAsync(Connect_to_ELMA_API.ELMA_SOAP.LoadContextRequest request) {
            return base.Channel.LoadContextAsync(request);
        }
        
        public System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.LoadContextResponse> LoadContextAsync(string userName, string password, long instanceId) {
            Connect_to_ELMA_API.ELMA_SOAP.LoadContextRequest inValue = new Connect_to_ELMA_API.ELMA_SOAP.LoadContextRequest();
            inValue.Body = new Connect_to_ELMA_API.ELMA_SOAP.LoadContextRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            return ((Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap)(this)).LoadContextAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Connect_to_ELMA_API.ELMA_SOAP.GetActiveTasksResponse Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap.GetActiveTasks(Connect_to_ELMA_API.ELMA_SOAP.GetActiveTasksRequest request) {
            return base.Channel.GetActiveTasks(request);
        }
        
        public Connect_to_ELMA_API.ELMA_SOAP.TaskInfo[] GetActiveTasks(string userName, string password, long instanceId) {
            Connect_to_ELMA_API.ELMA_SOAP.GetActiveTasksRequest inValue = new Connect_to_ELMA_API.ELMA_SOAP.GetActiveTasksRequest();
            inValue.Body = new Connect_to_ELMA_API.ELMA_SOAP.GetActiveTasksRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            Connect_to_ELMA_API.ELMA_SOAP.GetActiveTasksResponse retVal = ((Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap)(this)).GetActiveTasks(inValue);
            return retVal.Body.GetActiveTasksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.GetActiveTasksResponse> Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap.GetActiveTasksAsync(Connect_to_ELMA_API.ELMA_SOAP.GetActiveTasksRequest request) {
            return base.Channel.GetActiveTasksAsync(request);
        }
        
        public System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.GetActiveTasksResponse> GetActiveTasksAsync(string userName, string password, long instanceId) {
            Connect_to_ELMA_API.ELMA_SOAP.GetActiveTasksRequest inValue = new Connect_to_ELMA_API.ELMA_SOAP.GetActiveTasksRequest();
            inValue.Body = new Connect_to_ELMA_API.ELMA_SOAP.GetActiveTasksRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            return ((Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap)(this)).GetActiveTasksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Connect_to_ELMA_API.ELMA_SOAP.ExecuteTaskResponse Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap.ExecuteTask(Connect_to_ELMA_API.ELMA_SOAP.ExecuteTaskRequest request) {
            return base.Channel.ExecuteTask(request);
        }
        
        public void ExecuteTask(string userName, string password, long taskId, string connectorUid, Connect_to_ELMA_API.ELMA_SOAP.WebData data) {
            Connect_to_ELMA_API.ELMA_SOAP.ExecuteTaskRequest inValue = new Connect_to_ELMA_API.ELMA_SOAP.ExecuteTaskRequest();
            inValue.Body = new Connect_to_ELMA_API.ELMA_SOAP.ExecuteTaskRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.taskId = taskId;
            inValue.Body.connectorUid = connectorUid;
            inValue.Body.data = data;
            Connect_to_ELMA_API.ELMA_SOAP.ExecuteTaskResponse retVal = ((Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap)(this)).ExecuteTask(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.ExecuteTaskResponse> Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap.ExecuteTaskAsync(Connect_to_ELMA_API.ELMA_SOAP.ExecuteTaskRequest request) {
            return base.Channel.ExecuteTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.ExecuteTaskResponse> ExecuteTaskAsync(string userName, string password, long taskId, string connectorUid, Connect_to_ELMA_API.ELMA_SOAP.WebData data) {
            Connect_to_ELMA_API.ELMA_SOAP.ExecuteTaskRequest inValue = new Connect_to_ELMA_API.ELMA_SOAP.ExecuteTaskRequest();
            inValue.Body = new Connect_to_ELMA_API.ELMA_SOAP.ExecuteTaskRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.taskId = taskId;
            inValue.Body.connectorUid = connectorUid;
            inValue.Body.data = data;
            return ((Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap)(this)).ExecuteTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Connect_to_ELMA_API.ELMA_SOAP.SaveContextResponse Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap.SaveContext(Connect_to_ELMA_API.ELMA_SOAP.SaveContextRequest request) {
            return base.Channel.SaveContext(request);
        }
        
        public void SaveContext(string userName, string password, long instanceId, Connect_to_ELMA_API.ELMA_SOAP.WebData data) {
            Connect_to_ELMA_API.ELMA_SOAP.SaveContextRequest inValue = new Connect_to_ELMA_API.ELMA_SOAP.SaveContextRequest();
            inValue.Body = new Connect_to_ELMA_API.ELMA_SOAP.SaveContextRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            inValue.Body.data = data;
            Connect_to_ELMA_API.ELMA_SOAP.SaveContextResponse retVal = ((Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap)(this)).SaveContext(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.SaveContextResponse> Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap.SaveContextAsync(Connect_to_ELMA_API.ELMA_SOAP.SaveContextRequest request) {
            return base.Channel.SaveContextAsync(request);
        }
        
        public System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.SaveContextResponse> SaveContextAsync(string userName, string password, long instanceId, Connect_to_ELMA_API.ELMA_SOAP.WebData data) {
            Connect_to_ELMA_API.ELMA_SOAP.SaveContextRequest inValue = new Connect_to_ELMA_API.ELMA_SOAP.SaveContextRequest();
            inValue.Body = new Connect_to_ELMA_API.ELMA_SOAP.SaveContextRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            inValue.Body.data = data;
            return ((Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap)(this)).SaveContextAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Connect_to_ELMA_API.ELMA_SOAP.TerminateResponse Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap.Terminate(Connect_to_ELMA_API.ELMA_SOAP.TerminateRequest request) {
            return base.Channel.Terminate(request);
        }
        
        public void Terminate(string userName, string password, long instanceId, string reason) {
            Connect_to_ELMA_API.ELMA_SOAP.TerminateRequest inValue = new Connect_to_ELMA_API.ELMA_SOAP.TerminateRequest();
            inValue.Body = new Connect_to_ELMA_API.ELMA_SOAP.TerminateRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            inValue.Body.reason = reason;
            Connect_to_ELMA_API.ELMA_SOAP.TerminateResponse retVal = ((Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap)(this)).Terminate(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.TerminateResponse> Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap.TerminateAsync(Connect_to_ELMA_API.ELMA_SOAP.TerminateRequest request) {
            return base.Channel.TerminateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.TerminateResponse> TerminateAsync(string userName, string password, long instanceId, string reason) {
            Connect_to_ELMA_API.ELMA_SOAP.TerminateRequest inValue = new Connect_to_ELMA_API.ELMA_SOAP.TerminateRequest();
            inValue.Body = new Connect_to_ELMA_API.ELMA_SOAP.TerminateRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            inValue.Body.reason = reason;
            return ((Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap)(this)).TerminateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Connect_to_ELMA_API.ELMA_SOAP.SendMessageResponse Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap.SendMessage(Connect_to_ELMA_API.ELMA_SOAP.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public Connect_to_ELMA_API.ELMA_SOAP.WorkflowMessageSendResult SendMessage(string userName, string password, string messageTypeName, Connect_to_ELMA_API.ELMA_SOAP.WebData data) {
            Connect_to_ELMA_API.ELMA_SOAP.SendMessageRequest inValue = new Connect_to_ELMA_API.ELMA_SOAP.SendMessageRequest();
            inValue.Body = new Connect_to_ELMA_API.ELMA_SOAP.SendMessageRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.messageTypeName = messageTypeName;
            inValue.Body.data = data;
            Connect_to_ELMA_API.ELMA_SOAP.SendMessageResponse retVal = ((Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap)(this)).SendMessage(inValue);
            return retVal.Body.SendMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.SendMessageResponse> Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap.SendMessageAsync(Connect_to_ELMA_API.ELMA_SOAP.SendMessageRequest request) {
            return base.Channel.SendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.SendMessageResponse> SendMessageAsync(string userName, string password, string messageTypeName, Connect_to_ELMA_API.ELMA_SOAP.WebData data) {
            Connect_to_ELMA_API.ELMA_SOAP.SendMessageRequest inValue = new Connect_to_ELMA_API.ELMA_SOAP.SendMessageRequest();
            inValue.Body = new Connect_to_ELMA_API.ELMA_SOAP.SendMessageRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.messageTypeName = messageTypeName;
            inValue.Body.data = data;
            return ((Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap)(this)).SendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Connect_to_ELMA_API.ELMA_SOAP.SendMessageToInstanceResponse Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap.SendMessageToInstance(Connect_to_ELMA_API.ELMA_SOAP.SendMessageToInstanceRequest request) {
            return base.Channel.SendMessageToInstance(request);
        }
        
        public Connect_to_ELMA_API.ELMA_SOAP.WorkflowMessageSendResult SendMessageToInstance(string userName, string password, long instanceId, string messageTypeName, Connect_to_ELMA_API.ELMA_SOAP.WebData data) {
            Connect_to_ELMA_API.ELMA_SOAP.SendMessageToInstanceRequest inValue = new Connect_to_ELMA_API.ELMA_SOAP.SendMessageToInstanceRequest();
            inValue.Body = new Connect_to_ELMA_API.ELMA_SOAP.SendMessageToInstanceRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            inValue.Body.messageTypeName = messageTypeName;
            inValue.Body.data = data;
            Connect_to_ELMA_API.ELMA_SOAP.SendMessageToInstanceResponse retVal = ((Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap)(this)).SendMessageToInstance(inValue);
            return retVal.Body.SendMessageToInstanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.SendMessageToInstanceResponse> Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap.SendMessageToInstanceAsync(Connect_to_ELMA_API.ELMA_SOAP.SendMessageToInstanceRequest request) {
            return base.Channel.SendMessageToInstanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Connect_to_ELMA_API.ELMA_SOAP.SendMessageToInstanceResponse> SendMessageToInstanceAsync(string userName, string password, long instanceId, string messageTypeName, Connect_to_ELMA_API.ELMA_SOAP.WebData data) {
            Connect_to_ELMA_API.ELMA_SOAP.SendMessageToInstanceRequest inValue = new Connect_to_ELMA_API.ELMA_SOAP.SendMessageToInstanceRequest();
            inValue.Body = new Connect_to_ELMA_API.ELMA_SOAP.SendMessageToInstanceRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            inValue.Body.messageTypeName = messageTypeName;
            inValue.Body.data = data;
            return ((Connect_to_ELMA_API.ELMA_SOAP.WFPWebServiceSoap)(this)).SendMessageToInstanceAsync(inValue);
        }
    }
}
